#!/bin/sh

PASSWORD=$( head -c 12 /dev/urandom | base64 | tr -d "/" | tr -d "+" )
TOKEN=$( ./fex create )
TOKEN=$( ./fex passwd ${TOKEN} "$PASSWORD" )

FEX_URL=$( ./fex url ${TOKEN} )
echo "${FEX_URL} - $PASSWORD"

for file in "$@"
do
	./fex file ${TOKEN} add $file
done
