#!/bin/sh

TOKEN=$(./fex anonymous)
LINK=$(./fex create ${TOKEN})

echo "https://fex.net/s/${LINK}"

DIR=$(./fex dir ${TOKEN} add backup_`date +%Y%m%d%H%M%S`)

for file in "$@"
do
	./fex file ${TOKEN} add $file ${DIR}
done
